# Generated by Django 3.2.25 on 2024-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanderers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanderer',
            name='image',
            field=models.ImageField(default='../default_profileimage_abyxmi', upload_to='images/'),
        ),
    ]
